from typing import Protocol

from .entities import CourseCompletion, CourseReview


class CourseCompletionRepository(Protocol):
    async def has_access(self, student_id: str, course_id: str) -> bool: ...
    async def get_completion(self, student_id: str, course_id: str) -> CourseCompletion: ...
    async def complete_learn_more(
        self, student_id: str, course_id: str, lesson_id: str, block_id: str
    ) -> CourseCompletion: ...
    async def upsert_review(
        self, student_id: str, course_id: str, rating: int, title: str, comment: str
    ) -> CourseReview: ...
    async def list_reviews(self, course_id: str | None = None) -> list[CourseReview]: ...
