from typing import Protocol

from .entities import LiveEvent


class LiveEventRepository(Protocol):
    async def list_public(self) -> list[LiveEvent]: ...
    async def list_for_teacher(self, teacher_id: str, is_super_admin: bool) -> list[LiveEvent]: ...
    async def get_by_id(self, event_id: str) -> LiveEvent | None: ...
    async def create(self, instructor_id: str, data: dict) -> LiveEvent: ...
    async def update(self, event_id: str, data: dict) -> LiveEvent: ...
    async def delete(self, event_id: str) -> None: ...
